version: '3'

services:

  sample_db:
    image: postgres:10.6-alpine
    container_name: sample_db
    environment:
      - POSTGRES_DB=DatabaseName
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
    command:
      - -c
      - max_prepared_transactions=100
    ports:
      - "5433:5432" 
      
  pms_api:
    image: sampleapiimage
    container_name: sample_api_container
    environment:
        - ConnectionStrings:Default=Server=host.docker.internal;Port=5433;Database=DatabaseName;User Id=dbadmin;Password=dbadmin;
    ports:
      - "3452:80"      

